const test=require('node:test');const assert=require('node:assert/strict');const ui=require('../dist/branch_ui.js');
test('explicit requests offer mode; incidental or quoted instructions do not',()=>{
 for(const input of ['Start a branch run for these changes','Please complete this job on a feature branch','Build the utilities on a new feature branch'])assert.equal(ui.intent(input),'offer',input);
 for(const input of ['What is a feature branch?','The branch is feature/parser','Summarize this document','"Start a branch run"','> Start a branch run','`Start a branch run`','Explain how to start a branch run','Do not start a branch run'])assert.equal(ui.intent(input),'interactive',input);
});
function fixture(){const receipt={stage:'completed',item_id:'one',run_id:'run',new_tip:'a'.repeat(40),outcome:'changed'};return {branch_run:{id:'run',status:'running',feature_ref:'refs/heads/feature/job',target_ref:'refs/heads/main',current_item_id:'two',items:[{id:'one',title:'CSV parser',status:'committed',commit_receipt:receipt},{id:'two',title:'CLI',status:'working'}],events:[{id:'event',kind:'item_completed',detail:{item_id:'one',commit:receipt.new_tip}}]}};}
test('durable item receipts project outcomes and deduplicate milestones across polling',()=>{const task=fixture();task.branch_run.events.push(task.branch_run.events[0]);const p=ui.projectRun(task);assert.equal(p.milestones.length,1);assert.equal(p.current,2);assert.equal(p.items[0].commit,'a'.repeat(40));assert.deepEqual(ui.projectRun(task),p);});
test('pending commits and wrong receipt or event SHA never appear completed',()=>{const task=fixture();task.branch_run.items[0].commit_receipt.stage='intent';assert.equal(ui.projectRun(task).items[0].done,false);assert.equal(ui.projectRun(task).milestones.length,0);task.branch_run.items[0].commit_receipt.stage='completed';task.branch_run.items[0].commit_receipt.item_id='other';assert.equal(ui.projectRun(task).items[0].done,false);task.branch_run.items[0].commit_receipt.item_id='one';task.branch_run.events[0].detail.commit='b'.repeat(40);assert.equal(ui.projectRun(task).milestones.length,0);});
test('reviewed no-change has no fake commit; finalizing is not ready or merged',()=>{const task=fixture(),item=task.branch_run.items[0];item.status='satisfied_without_change';item.commit_receipt.outcome='satisfied_without_change';task.branch_run.events[0].detail.commit=null;task.branch_run.status='finalizing';const p=ui.projectRun(task);assert.equal(p.items[0].unchanged,true);assert.equal(p.items[0].commit,null);assert.equal(p.ready,false);assert.equal(p.merged,false);task.branch_run.status='merged';assert.equal(ui.projectRun(task).label,'Confirming integration');task.branch_run.merge_receipt={stage:'completed'};assert.equal(ui.projectRun(task).merged,true);});
test('untrusted titles and diff text can be escaped safely',()=>assert.equal(ui.escape('<script>"&'), '&lt;script&gt;&quot;&amp;'));
test('cumulative diff keeps first and last files and continuation pages',()=>{const text='diff --git a/first b/first\n-old\n+new\ndiff --git a/last b/last\n+last\n';const sections=ui.diffSections(text);assert.equal(sections.length,2);assert.match(sections[0].text,/-old/);assert.match(sections[1].text,/last/);assert.equal(ui.diffSections('+page continuation')[0].title,'Diff continuation');assert.equal(sections.map(s=>s.text).join(''),text);});
test('manual composer limits map to cumulative units without per-request fields',()=>{assert.deepEqual(ui.proposedLimits({dollars:2,run_minutes:45,worker_turns:12,iterations:5,checkpoint_turns:6,output_tokens:1024,reviewer_tokens:50000,check_seconds:120}),{dollars:2,working_seconds:2700,output_tokens:1024,reviewer_tokens:50000,check_seconds:120});assert.equal(ui.proposedLimits().working_seconds,900);assert.throws(()=>ui.proposedLimits({run_minutes:Infinity}));assert.throws(()=>ui.proposedLimits({dollars:NaN}));});
test('paused finalization exposes recheck only after all recorded outcomes completed',()=>{const task=fixture();task.branch_run.status='paused';assert.equal(ui.projectRun(task).canRecheck,false);task.branch_run.items.pop();assert.equal(ui.projectRun(task).canRecheck,true);task.branch_run.items[0].commit_receipt.stage='intent';assert.equal(ui.projectRun(task).canRecheck,false);});
test('resume results distinguish fresh consent from saved merge recovery',()=>{assert.equal(ui.resumeAction({needs_consent:true}),'consent');assert.equal(ui.resumeAction({needs_merge_recovery:true,needs_consent:true}),'merge_recovery');assert.equal(ui.resumeAction({needs_consent:false,task:{}}),'resumed');const task=fixture();task.branch_run.items.pop();task.branch_run.status='paused';task.branch_run.merge_operation={id:'saved'};const p=ui.projectRun(task);assert.equal(p.pendingMerge,true);assert.equal(p.canRecheck,false);});
test('new chat without revision marker never routes into revision submission',()=>{assert.equal(ui.isRevisionTarget(null,undefined),false);assert.equal(ui.isRevisionTarget(undefined,undefined),false);assert.equal(ui.isRevisionTarget({id:'task'},undefined),false);assert.equal(ui.isRevisionTarget({id:'task'},'other'),false);assert.equal(ui.isRevisionTarget({id:'task'},'task'),true);});
test('branch activity keeps Pause available across intermediate approval and finalization',()=>{for(const status of ['running','finalizing','merging'])assert.equal(ui.isBusy({status:'approved',branch_run:{status}}),true);assert.equal(ui.isBusy({status:'approved',branch_run:{status:'ready_for_merge'}}),false);assert.equal(ui.isBusy({status:'reviewing',branch_run:{status:'paused'}}),false);assert.equal(ui.isBusy({status:'reviewing'}),true);assert.equal(ui.isBusy(null),false);});
test('actual event renderer accepts branch review and checkpoint metadata without legacy fields',()=>{const fs=require('node:fs'),vm=require('node:vm');const source=fs.readFileSync(require.resolve('../dist/app.js'),'utf8');const match=source.match(/function eventDetail\(event\) \{[\s\S]*?\n\}(?=\nfunction sourceLink)/);assert.ok(match);const render=vm.runInNewContext('('+match[0]+')',{esc:ui.escape});assert.match(render({kind:'review',detail:{item_id:'one',candidate_id:'candidate'}}),/Review event/);assert.doesNotThrow(()=>render({kind:'review'}));const checkpoint=render({kind:'checkpoint',title:'Reviewing branch item',detail:{item_id:'one',candidate_id:'candidate'}});assert.match(checkpoint,/Reviewing branch item/);assert.doesNotMatch(checkpoint,/undefined|data-checkpoint/);});
test('active duration shows seconds for short runs and minutes with remaining seconds',()=>{assert.equal(ui.duration(12.9),'12s');assert.equal(ui.duration(65),'1m 5s');assert.equal(ui.duration(0),'0s');});
test('saved unattended proposals retain their mode before authorization',()=>{assert.equal(ui.hasRun(null),false);assert.equal(ui.hasRun({id:'ordinary'}),false);assert.equal(ui.hasRun({branch_run:{status:'awaiting_authorization',authorization_ref:null}}),true);assert.equal(ui.hasRun({branch_run:{status:'running',authorization_ref:'approved'}}),true);});
test('saved terminal previews remain readonly after leave or merge',()=>{assert.equal(ui.terminalRun({branch_run:{status:'left_on_branch'}}),true);assert.equal(ui.terminalRun({branch_run:{status:'merged'}}),true);assert.equal(ui.terminalRun({branch_run:{status:'ready_for_merge'}}),false);assert.equal(ui.terminalRun(null),false);});

test("measurement status requires explicit plan opt-in", () => {
 const base={branch_run:{schema_version:1,id:"run",status:"running",items:[],plan:{measurement:true}}};
 assert.equal(ui.projectRun(base).measurement,true);
 base.branch_run.plan.measurement=false;
 assert.equal(ui.projectRun(base).measurement,false);
});
